# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Research"
  identifier = "Research"
  weight = 30

[[main]]
  name = "Recent publications"
  parent = "Research"
  url = "#featured"
  weight = 40

[[main]]
  name = "Publications"
  parent = "Research"
  url = "#publications"
  weight = 43
  
[[main]]
  name = "Working papers"
  parent = "Research"
  url = "#workingpapers"
  weight = 45
  
[[main]]
  name = "Projects"
  url = "#projects"
  weight = 58

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 55

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "CV"
    url = "cv/eborghettocv.pdf"
    weight = 15 
    
