---
title: "CV"
author: "Enrico Borghetto"
fontfamily: mathpazo
output:
  html_document:
    toc: true
    toc_float: true  
    theme: united
  word_document:
    toc: true
  pdf_document:
    toc: true
    latex_engine: pdflatex
    template: C:\Users\Enrico Borghetto\Dropbox\blog\R\svm-latex-cv.tex
fontsize: 11pt
geometry: margin=1in
jobtitle: FCT Investigator
linkcolor: blue
fontfamilyoptions: sc, osf
email: enrico.borghetto@unifi.it
updated: no
urlcolor: blue
web: enricoborghetto.netlify.com
---

```{r, echo=FALSE, cache=FALSE}
df <- Sys.Date()
```
Last updated: `r Sys.Date()`

## WORK ADDRESS
Dipartimento di Scienze Politiche e Sociali   
Università degli Studi di Firenze    
via delle Pandette, 32 (Building D1) 3rd floor, Florence, FI 50127  

## ACADEMIC APPOINTMENTS
* **04/2020-PRESENT**	Assistant Professor, Department of Political and Social Sciences (DSPS)   
University of Florence, Italy      

* **11/2019-PRESENT**	Researcher, contract funded by the Fundação para a Ciência e a Tecnologia at IPRI, Faculty of Social and Human Sciences (FCSH)  
University NOVA of Lisbon, Portugal  

* **03/2015-10/2019**	FCT investigator, contract funded by the Fundação para a Ciência e a Tecnologia (IF/00382/2014) at CICS.NOVA, Faculty of Social and Human Sciences (FCSH)  
University NOVA of Lisbon, Portugal   
    
* **01/2013-02/2015**	Postdoctoral Researcher at CESNOVA, FCSH, with a project entitled "The policy agenda at the time of crisis in Europe's periphery" (Bolsas de Pós-Doutoramento (BPD) funded by the Fundação para a Ciência e a Tecnologia, SFRH/BPD/89968/2012)   
University NOVA of Lisbon, Portugal   
    
* **11/2008-11/2012**	Postdoctoral Researcher, Department of Social and Political Studies with a project entitled "The europeanisation of executive-legislative relations: national parliaments and Community legislation"   
University of Milan, Milano, Italy   
    
## EDUCATION
* **09/2003-07/2007**	Ph.D. in Political Studies  
    Graduate School in Social, Economic and Political Sciences of the University of Milan  
    Dissertation: 'Non-compliance with the transposition deadlines of EU directives: the Italian case. Explaining transposition of EU directives into Italian legislation' (written in English and discussed on 17/07/2007) Supervisor: Prof. Marco Giuliani, Examination Committee Chair: Prof. Maurizio Ferrera
    
* **09/1998-07/2003**	University Degree in International and Diplomatic Sciences (110/110 magna cum laude)  
    University of Bologna (Forlì), Faculty of International and Diplomatic Sciences   
    Dissertation: "The accountability of international organisations: the Principal -Agent model applied to the WTO and the IMF". Supervisor: Prof. Salvatore Vassallo
    
* **1993-1998**	High School Diploma in Foreign Languages (English, French and German)  
    Liceo Linguistico sperimentale A.Canova, Treviso

## RESEARCH EXPERIENCE

### CURRENT PROJECTS
* **2015-PRESENT** One of the Principal investigators for the Portuguese Policy Agendas Project. This is a joint research project involving ISCTE and the FCSH https://www.comparativeagendas.net/portugal    

* **2009-PRESENT** One of the Principal investigators for the Italian Policy Agendas Project. This is a joint research project involving the NOVA University of Lisbon and the University of Lecce and Malta https://www.comparativeagendas.net/italy   
   
* **2020-PRESENT** Principal investigator for "ConstiRep: Constituency Service and policy representation in European Parliaments". This research project is funded by the Transnational Cooperation Program Pessoa (2020) and involves the FCSH and Lille University.  

### PAST PROJECTS
* **2015-2020** Principal investigator "Portuguese Parliament: Agenda-setting and Law-making" Exploratory Project financed by the Fundação para a Ciência e a Tecnologia (IF/00382/2014)      
   
* **2016-2020** Researcher in the project “Democracy in times of crisis: Power and Discourse in a three-level game”, Project financed by the Fundação para a Ciência e a Tecnologia (PTDC/IVC-CPO/2247/2014, coordinated by Catherine Moury, FCSH) URL: https://goo.gl/ExHizi   
  
* **2016-2020** Researcher in the project “Crisis, Political Representation and Democratic Renewal: The Portuguese case in the Southern European context”, Project financed by the Fundação para a Ciência e a Tecnologia (PTDC/IVC-CPO/3098/2014, coordinated by André Freire, Marco Lisi and Emmanouil Tsatsanis, FCSH and ISCTE-IUL) URL: https://goo.gl/HMBMaK    
   
* **2013-2015** Researcher in the project “Public preferences and Policy decision-making: a comparative analysis” Project financed by the Fundação para a Ciência e a Tecnologia (PTDC/IVC-CPO/3921/2012, coordinated by Ana Belchior, ISCTE-IUL)   

* **2014-2018** Principal investigator in the Portuguese team participating in the European project "Political Leaders in European Cities" (Coordinated by the University of Florence) This project deals with the role of Mayors and the transformation of political representation and careers at the local level.    
    
* **2010-2012** Co-manager of the ILMA (Italian-Law Making Database)  
    ILMA originated from an idea of a group of scholars affiliated with the Department of Social and Political Studies at the Universita' degli Studi di Milano, and it is one of the scientific products of the Center for the Observation of Legislatures (COoL). It is a relational database that combines information on Italian legislation, roll calls and political elites. It currently covers six Italian legislatures (1987-2008).
    
* **2010-2012** Member of the research unit of the University of Milan in the project -Institutional agenda setting: Actors, time, information.- co-financed by the Italian Ministry for Research and Higher Education (PRIN 2009, Protocol 2009TPW4NL_002, Principal Investigator: prof. Marco Giuliani).   
    
* **2008-2012**	Researcher in the Italian team participating in the European project "Delors' Myth: The scope and impact of Europeanization on law production". 
    The project aims are: 1) developing new methods to quantitatively measure the Europeanization of national public policies (i.e. the scope and extent national policies are shaped by EU law and policy); 2) analysing the impact of EU policy-making on the relationship between government and parliament in each of the nine countries under study.   
    
* **2006** Research assistant at the Research Unit on European Governance (URGE)  
    Collegio Carlo Alberto di Moncalieri, Torino, Italy  
    Key areas of responsibility: review of the literature relevant for URGE projects; assistance in the preparation of manuscripts and reports; management of events organized by URGE.
    
* **Jan/Aug 2005** 	Research assistant for the project: "Compliance with EU Law: Explaining the Transposition of EU Directives" (Coordinator: Prof. Fabio Franchino)  
    University College London, School of Public Policy, London, UK    
    Key areas of responsibility: data collection and maintenance of the database on national transposition of EU directives; review of the literature on EU Compliance; contribution to joint publications.   
    
* **Oct/Dec 2004** 	Research assistant for the project "Political representation and legislative process in the regions and the autonomous provinces in Italy" (Coordinator Prof. Salvatore Vassallo)   
    Istituto Carlo Cattaneo and Universita' di Bologna, Bologna, Italy   
    Key areas of responsibility: assistance in drafting the questionnaire; interviews with over 30 members of the Lombardia Regional Council.   
    
### VISITING RESEARCH PERIODS
* **May 2019** Visiting Researcher, IDC Herzliya    
    Tel Aviv, Israel      
    
* **Sept 2017/Jan 2018** Visiting Researcher, Department of Government  
    University of Texas, Austin, USA   
    
* **Feb/Mar 2012** Visiting Fellow Mannheim Centre for European Social Research (MZES)    
    University of Mannheim, Mannheim, Germany
    
* **Jun/Aug 2010** Visiting Fellow, Center for American Politics and Public Policy (CAPPP)    
    University of Washington, Seattle, USA

* **Jan/Aug 2005** Visiting Fellow, School of Public Policy    
    University College London, London, UK   
  
## TEACHING EXPERIENCE    
### WHOLE COURSES:  
* **06/04/2020-30/05/2020** “Comparative Politics”, Undergraduate course, University of Florence, 9 ECTS (32 hours)    
   
* **18/02/2020-30/05/2020** “Analise Politica Comparada”, Undergraduate course, FCSH, Nova University of Lisbon, 6 ECTS (64 hours)   
   
* **10/02/2020-13/02/2020** “Research design”, Lisbon Winter School in Research Skills and Methods, FCSH, NOVA University of Lisbon, 2 ECTS (12 hours)   
   
* **03/10/2019-17/12/2019** Course for PhD students “The Maestri of Political Science”, FCSH, Nova University of Lisbon (20 hours)   
  
* **21/02/2019-30/05/2019** “Parliamentary Studies”, Master Course, FCSH, Nova University of Lisbon, 10 ECTS (44 hours)  
  
* **21/02/2019-30/05/2019** Tutorial for undergraduate students “Portuguese Parliament: Agenda-setting and Law-making”, FCSH, Nova University of Lisbon, 6 ECTS (20 hours)    
  
* **04/02/2019-07/02/2019** “Research design”, Lisbon Winter School in Research Skills and Methods, FCSH, NOVA University of Lisbon, 2 ECTS (12 hours)   
  
* **27/08/2018-05/09/2018** “The Essentials of Data Analysis in R”, Lisbon Summer School, FCSH, NOVA University of Lisbon, 2 ECTS (25 hours)   
   
* **21/02/2018-30/05/2018** “Politics in challenging times. Populism, protests and the crisis of representation after the Great Recession”, Master Course, FCSH, Nova University of Lisbon, 10 ECTS (44 hours)   
   
* **05/02/2018-08/02/2018** “Research design”, Lisbon Winter School in Research Skills and Methods, FCSH, NOVA University of Lisbon, 2 ECTS (12 hours)   
  
* **21/02/2017-30/05/2017** Tutorial for undergraduate students “Portuguese Parliament: Agenda-setting and Law-making”, FCSH, Nova University of Lisbon, 6 ECTS (20 hours)         
  
* **30/01/2017-02/02/2017** “The Essentials of Quantitative Research. Data Analysis in R” Lisbon Winter School in Research Skills and Methods, FCSH, NOVA University of Lisbon, 2 ECTS (12 hours)    
  
* **29/8/2016-02/09/2016** “The Essentials of Data Analysis in R” Lisbon Summer School, FCSH, NOVA University of Lisbon (15 hours)    
  
* **02/03/2016-25/05/2016** “The political and social consequences of the Great Recession in Southern Europe”, Master Course, FCSH, Nova University of Lisbon, 10 ECTS (44 hours)    
  
* **07/03/2016-10/03/2016** “The Essentials of Quantitative Research. Data Analysis in R” Lisbon Winter School in Research Skills and Methods, FCSH, NOVA University of Lisbon, 2 ECTS (12 hours)     
  
* **09/03/2015-12/03/2015** “The Essentials of Quantitative Research. Data Analysis in R” Lisbon Winter School in Research Skills and Methods, FCSH, NOVA University of Lisbon, 2 ECTS (12 hours)    
  
* **10/02/2014-13/02/2014** "The Essentials of Quantitative Research. Data Analysis in R" Lisbon Winter School in Research Skills and Methods, NOVA University of Lisbon, 2 ECTS (12 hours)   
  
* **03/05/2013-08/05/2013** “Introduction to Event History Analysis with STATA”, Graduate School of the University of Milan, 2 ECTS (12 hours)    
  
* **13/02/2013-16/02/2013** “Introduction to Event History Analysis” Lisbon Winter School in Research Skills and Methods, FCSH, NOVA University of Lisbon, 2 ECTS (12 hours)    
   

### ONE-OFF CLASSES:   
* **30/10/2019** “Populism”, class for the undergraduate course in Sociology, FCSH, NOVA University of Lisbon   

* **30/04/2015** “The European Crisis”, class for the cycle of seminars for Master students in “European politics”, FCSH, NOVA University of Lisbon   
  
* **15/04/2015** “Europeanization of Portugal”, class for the cycle of seminars for Master students in “Ciência Política e Relações Internacionais”, FCSH, NOVA University of Lisbon   
  
* **23/11/2014** “The Portuguese parliament in a comparative perspective”, class for the cycle of seminars for Erasmus students “Portuguese Politics and Society”, FCSH, NOVA University of Lisbon   
  
* **28/04/2014** 1-day workshop “The political fallouts of the Great Depression”, ASEU - Jean Monnet Module on Agenda-Setting in the European Union, University of Malta, Malta   
  
* **14/11/2013** “The Portuguese parliament in a comparative perspective”, class for the cycle of seminars for Erasmus students “Portuguese Politics and Society”, FCSH, November 2013    
    
* **2010-2012** Teaching assistant for the postgraduate course “Democratic Governance and Public Administration: The European Union” (Prof.Fabio Franchino) University of Milan, Faculty of Political Science, Master in Economics and Political Science   
  
* **2006-2011** Teaching assistant for the undergraduate course “Introduction to Political Science” (Prof. Fabio Franchino) University of Milan, Faculty of Political Science, Degree in International studies and European institutions   
  

## GRANTS AND AWARDS
* 2019 "Carlo Maria Santoro” Award for best paper presented in the 2018 Annual Conference of the Italian Political Science Association   

* 2015-20 “Portuguese Parliament: Agenda-setting and Law-making” FCT Investigator Contract and Exploratory Project financed by the Fundação para a Ciência e a Tecnologia (IF/00382/2014)   
   
*	2018 Selected for the International Credit Mobility project, under the Erasmus+ programme for a research period at IDC - Interdisciplinary Center Herzliya (IDC), application CM18AC0249    
   
*	2016 Contrato Erasmum + - Açâo Chave I – Mobilidade Individual para fins de aprendizagem – Contrato 29191/007/2016/STT   
   
* Part of the research team located in Milan university awarded the PRIN funding in both 2007 (prot. scrwt4) and 2009 (prot. 2009TPW4NL_002). PRIN= Research Programs of National Relevance awarded by the Italian Ministry of Education and Research

* Research Unit on European Governance (URGE) - 1-year research grant

* PhD scholarship (2003-2007) by the Italian Ministry of Education and Research

* 6-month scholarship in 2002 to conduct undergraduate thesis research in the UK (awarded by the University of Bologna-Forlì)

* 9-month Erasmus scholarship in 2000, University of Sussex, UK

## PUBLICATIONS  

### ARTICLES IN ACADEMIC JOURNALS
* Epp DA and Borghetto E (forthcoming) Legislative Agendas during Periods of Inequality: Evidence from Europe and the United States. Journal of European Public Policy.   

* Borghetto E, Santana‐Pereira J and Freire A (2020) Parliamentary Questions as an Instrument for Geographic Representation: The Hard Case of Portugal. Swiss Political Science Review 26(1): 10-30. DOI: 10.1111/spsr.12387.    

*	Borghetto E and Belchior AM (2020) Party Manifestos, Opposition and Media as Determinants of the Cabinet Agenda. Political Studies 68(1): 37–53. DOI: 10.1177/0032321718820738.   

* Borghetto E (2018) Challenger parties in Parliament: the case of the Italian Five Star Movement. Italian Political Science 13(3): 19–32.  

* Lisi M and Borghetto E (2018) Populism, Blame Shifting and the Crisis: Discourse Strategies in Portuguese Political Parties. South European Society and Politics 23(4): 405–427. DOI: 10.1080/13608746.2018.1558606    

* Borghetto E, Carammia M and Russo F (2018) Policy agendas in Italy: introduction to the special issue. Italian Political Science Review / Rivista Italiana di Scienza Politica 48(3): 265–274. DOI: 10.1017/ipo.2018.17     
	
* Carammia M, Borghetto E and Bevan S (2018) Changing the transmission belt: the programme-to-policy link in Italy between the First and Second Republic. Italian Political Science Review / Rivista Italiana di Scienza Politica 48(3): 275–288. DOI: 10.1017/ipo.2018.13     

* Borghetto E and Lisi M (2018) Productivity and Reselection in a Party-based Environment: Evidence from the Portuguese Case. Parliamentary Affairs 71(4): 868–887. DOI: 10.1093/pa/gsx051    

* Borghetto E (2018) Delegated decree authority in a parliamentary system: the exercise of legislative delegation in Italy (1987–2013). The Journal of Legislative Studies 24(2): 179–196. DOI: 10.1080/13572334.2018.1439441    

* Borghetto E and Russo F (2018) From agenda setters to agenda takers? The determinants of party issue attention in times of crisis. Party Politics 24(1): 65–77. DOI: 10.1177/1354068817740757   

* Borghetto E, Visconti F and Michieli M (2017) Government Agenda-Setting in Italian Coalitions. Testing the «Partisan Hypothesis» Using Italian Investiture Speeches 1979- 2014. Rivista Italiana di Politiche Pubbliche (2/2017): 193–220. DOI: 10.1483/87214    

* Borghetto E (2015) Challenging Italian centralism through the vertical shift of competences to the subnational and supranational levels. Contemporary Italian Politics 7(1): 58–75. DOI: 10.1080/23248823.2014.1002260.    

* Borghetto E (2014) Legislative processes as sequences: Exploring temporal trajectories of Italian law-making by means of sequence analysis. International Review of Administrative Sciences 80(3): 553–76.    

* Borghetto E and Mäder L (2014) EU law revisions and legislative drift. European Union Politics 15(2): 171–191. DOI: 10.1177/1465116513513345   

* Borghetto E and Giuliani M (2012) A Long Way to Tipperary: Time in the Italian Legislative Process 1987–2008. South European Society and Politics 17(1): 23–44. DOI: 10.1080/13608746.2012.654619.    

* Borghetto E, Curini L, Giuliani M, et al. (2012) Italian Law-Making Archive: A new tool for the analysis of the Italian legislative process. Rivista Italiana di Scienza Politica 2012(3): 481–502.  
   
* Borghetto E and Carammia M (2010) L’analisi comparata delle agende politiche: il Comparative Agendas Project. Rivista Italiana di Scienza Politica 2(Agosto 2010): 301–315.   

* Borghetto E and Franchino F (2010) The Role of Subnational Authorities in the Implementation of EU Directives. Journal Of European Public Policy 17(6): 759–780.
   
* Borghetto E, Giuliani M and Zucchini F (2009) Quanta Bruxelles c’è a Roma? L’europeizzazione della produzione normativa italiana. Rivista italiana di Politiche Pubbliche 2009(1): 135–162.   

* Borghetto E, Franchino F and Giannetti D (2006) Complying with the transposition deadlines of EU directives: Evidence from Italy. Rivista italiana di Politiche Pubbliche 1(2006): 7–38. 

### CHAPTERS IN EDITED BOOKS
* Borghetto E and Lisi M (forthcoming) Legislative Activities before and after the Great Recession: An Analysis of Unemployment and Social Welfare Issues. In: Lisi M, Freire A, and Tsatsanis E (eds) Political Representation and Citizenship in Portugal. Lanham, Maryland: Lexington Books, pp. 173–191.   

* Carammia M, Borghetto E and Sousa Galito M (2019) A Agenda do Conselho Europeu face às Crises. In: Camisão I and Brandão AP (eds) O Estado Da União Europeia: Da(s) Crise(s) à Mudança? Petrony, pp. 23–42.  

* Belchior AM and Borghetto E (2019) The Portuguese Policy Agendas Project. In: Baumgartner FR, Breunig C, and Grossman E (eds) Comparative Policy Agendas: Theory, Tools, Data. Oxford, New York: Oxford University Press. 145-151   

* Borghetto E and Chaques-Bonafont L (2019) Parliamentary Questions. In: Baumgartner FR, Breunig C, and Grossman E (eds) Comparative Policy Agendas: Theory, Tools, Data. Oxford, New York: Oxford University Press. 282-299   

* Borghetto E, Carammia M and Russo F (2019) The Italian Agendas Project. In: Baumgartner FR, Breunig C, and Grossman E (eds) Comparative Policy Agendas: Theory, Tools, Data. Oxford, New York: Oxford University Press. 120-128  
   
* Koprić I, Hlynsdóttir EM, Džinić J, et al. (2018) Institutional environments and mayors’ role perceptions. In: Heinelt H, Magnier A, Cabria M, et al. (eds) Political Leaders and Changing Local Democracy: The European Mayor. 1st ed. 2018 edition. Palgrave Macmillan, pp. 149–173    

* Borghetto E (2015) Questioning the Government in Time of Crisis. An Analysis of Question Time in Spain. In: Preunkert, J, Baptista L, and Vobruba G (eds) Aftermath. Political and Urban Consequences of the Euro Crisis. Lisbon: Edições Colibri, pp. 91–116.   

* Borghetto E and Carammia M (2015) Party Priorities, Government Formation, and the Making of the Executive Agenda. In: Conti N and Marangoni F (eds) The Challenge of Coalition Government: The Italian Case. Abingdon: Routledge, pp. 36–57.     

* Borghetto E and Visconti F (2015) Governing by revising. A study on post-enactment policy change in Italy. In: Conti N and Marangoni F (eds) The Challenge of Coalition Government: The Italian Case. Abingdon: Routledge, pp. 106–127.     

* Borghetto E, Carammia M and Zucchini F (2014) The Impact of Party Policy Priorities on Italian Law-Making from the First to the Second Republic (1983-2006). In: Walgrave S and Green-Pedersen C (eds) Agenda Setting, Policies, and Political Systems. Chicago: Chicago University Press, pp. 164–182.   
   
* Borghetto E, Giuliani M and Zucchini F (2012) Leading governments and unwilling legislators. The European Union and the Italian Law making (1987-2006). In: Brouard S, Costa O, and König T (eds) The Europeanization of Domestic Legislatures. New York: Springer, pp. 109–130.    

### BOOKS

* Borghetto E (2013) Keeping the Pace with Europe: Non-Compliance with the Transposition Deadline of EU Directives in the Italian Case. Novi Ligure: Epoke Edizioni.   

### OTHER RESEARCH OUTPUTS  
* Borghetto E (2018) "Anti-populism", in F.José Eduardo (Ed) Dicionário dos Antis. A Cultura Portuguesa em Negativo, Imprensa Nacional-Casa da Moeda  

* Borghetto E (2016) Review ‘Crise Económica, Políticas de Austeridade e Representação Política, Lisboa, Assembleia da República – Divisão de edições, 2015’. Analise Social 219: 462–466    

* Borghetto E, De Giorgi E and Lisi M (2014) Government failure, opposition success? Parties electoral performance in Portugal and Italy at the time of the crisis.Jean Monnet Occasional Paper, No.05/2014, Institute for European Studies (Malta).    

* Borghetto E (2007) The respect of transposition deadlines in Italy: do political priorities matter? URGE Working paper 7/2007    

## WORK IN PROGRESS  
   
* with Emmanouil Tsatsanis, José Ramón Montero, André Freire. What kind of democrats? Ideological and generational gaps in forms of support for democracy in Southern Europe in the aftermath of the economic crisis. [under review]   

* with Julie Sevenans, Emiliano Grossman. Seeking information or pressing for action: analysing the function of parliamentary questions in a comparative perspective. [under review] 

* with	Federico Russo, Marco Lisi. Persistent politicisation or temporary perturbation? The policy content of question time during and after the peak of the crisis in Italy, Portugal and Spain   

* The issue strategies of niche parties between elections: an analysis of question time in six countries. Working paper  [under review]   

* with Kartalis Yani, The Parliamentary Scrutiny of EU Affairs after the Eurocrisis: Evidence from Southern Europe. Working paper  

* with Amnon Cavari, Maoz Rosenthal, Ilana Shpizeman, Gilad Greenwald, Private Member’s bills in the Knesset. Working paper   

   
## CONFERENCE PAPERS (A SELECTION)  
* "The impact of the crisis on issue competition in Italy, Portugal and Spain: evidence from an analysis of question time", September 2019, Annual Conference of the Italian Political Science Association, Lecce   

* "The Parliamentary Scrutiny of EU Affairs after the Eurocrisis: Evidence from Southern Europe", September 2019, ECPR General Conference 2019, Wroclaw   

* "The ‘Invisible’ Local Representation: District-Based Representation in a One-District Electoral System", June 2019, Comparative Agendas Project, Budapest   

* "True to your past or looking ahead: the dynamics of government agenda-setting", June 2019, Comparative Agendas Project, Budapest       

* “Legislative Agendas in an Age of Inequality”, May 2019, Lauder School Faculty Seminar, IDC Herzliya, Israel      
    
* "The issue strategies of niche parties between elections: an analysis of question time in six countries.",September 2018, ECPR General Conference, Hamburg     

* "What kind of democrats? Ideological and generational gaps in forms of support for democracy in Southern Europe in the aftermath of the economic crisis", September 2018, ECPR General Conference, Hamburg      

* "Seeking information or pressing for action: analysing the function of parliamentary questions in a comparative perspective.", July 2018, Comparative Agendas Project, Amsterdam    

* "Economic inequality and legislative agendas in Europe" 18-20 April 2018, Conference of the Portuguese Political Science Association, Braga     

*	"Constituency characteristics, civil society links and topic selection by individual legislators: Evidence from Portugal", April 2018, ECPR Joint Session, Nicosia      

*	"The determinants of the executive weekly agenda in Portugal: party mandates vs media attention", 6th December, 2017, University of Texas, Austin   

*	"The Five-Star Movement in Parliament: a Truly New Kind of Parliamentary Opposition?", 14-16 September 2017, Annual Conference of the Italian Political Science Association, Urbino  

*	"Constituency Characteristics, Expertise, Civil Society Links and Parliamentary Questions: Evidence from Portugal.", 6-9 September 2017, ECPR General Conference, Oslo    

*	"Populism, blame shifting and the crisis: communication strategies in Portuguese political parties", 6-9 September 2017, ECPR General Conference, Oslo  

*	"The determinants of the executive weekly agenda in Portugal: party mandates vs media attention" June 15-17, 2017, Annual Conference of the Comparative Agendas network, Edinburgh  

* "Delegated decree authority in a parliamentary system. The exercise of legislative delegation in Italy" (1987-2013), 15-17 September 2016, SISP Annual Conference, University of Milan     
   
*  "Parliamentary Questions and Individual Representation in a Party-Dominated Environment: Evidence from Portugal", July 23-28, 2016, IPSA World Congress - International Political Science Association, Poznan, Poland   
     
* "Parliamentary Questions and Individual Representation in a Party-Dominated Environment: Evidence from Portugal", June 30 to July 2 2016, ECPR Standing group on parliaments, University of Munich   
    
* "Between contraction of agendas and issue expansion: The impact of the Euro crisis on partiesan issue attention", 27-29 June 2016, Annual Conference Comparative Agendas Project, University of Geneva.   
   
* "The determinants of party issue attention in time of crisis: from agenda setters to agenda takers?", 
10-12 March, 2016, Portuguese Association of Political Science, Nova University of Lisbon.  

* "Challenging the government in parliament: an analysis of question time in time of austerity", 
Workshop - O Lusitanismo Italiano" 17-18 December, 2015, University of Bologna.  
   
* "Challenging the government in parliament: an analysis of question time in time of austerity", 
Workshop - Party Competition and Political Representation in Crisis: A Comparative Perspective" 24-25 September, 2015, at the European University Institute, Florence.       
   
* "The transmission of policy agendas. The effect of party competition on the gap between electoral priorities and policy outputs", 22-24 June 2015, Annual Conference Comparative Agendas Project, University of Lisbon  
  
* "The impact of party priorities on Portuguese legislative activities", 22-24 June 2015, Annual Conference Comparative Agendas Project, University of Lisbon  
   
* "Questioning the government in time of crisis. A comparative analysis of the content of parliamentary questions in Italy, Portugal and Spain", 20-21 November 2014,  Workshop "Policy-Making in Hard Times: Southern European Countries in a Comparative Perspective", Institut Barcelona d'Estudis Internacionals (IBEI) & Instituto Carlos III-Juan March de Ciencias Sociales (IC3JM), Madrid   

* "Challenging Italian centralism: the vertical shift of competences to the subnational and supranational level". 11-13 September 2014, SISP Annual Conference, University of Perugia    

* "Exploring Bill Winnowing in the Italian Chamber of Deputies (1996-2012)",  11-12 July 2014, Workshop "Parliamentary Scrutiny of EU Politics" Heidelberg University   
  
* "Agenda-setting in times of crisis", 24-26 July 2014, Workshop "Changes to political representation in Southern Europe in times of crisis", University of Nottingham, UK  
   
* "Questioning the government in times of crisis", 14-16 April 2014, Biannual Conference Portuguese Political Science Association, Coimbra   
   
* "The political fallouts of the Great Depression", 28 April 2014, ASEU - Jean Monnet Module on Agenda-Setting in the European Union, University of Malta, Malta   

*	"Tracking attention to issues as a way to learn about political systems", 23 October 2013, INESD, Instituto de Engenharia de Sistemas e Computadores, Investigação e Desenvolvimento, Lisboa   
   
*	"Government Agenda-Setting in Italian Coalitions: An analysis of investiture speeches in Italy 1979-2013", 12-14 September 2013, SISP Annual Conference, Florence 

*	"The Influence of Coalition Parties on Governments' Legislative Agendas in Italy Between the First and Second Republic". 27-29 June 2013, Annual Conference Comparative Agendas Project, Antwerp

*	"The evolution of Italian law. A study on post-enactment policy change between the 1st and 2nd Italian Republic", 13-15 September 2012, SISP Annual Conference, Rome   

* "Italian: Law-Making Archive: A New Tool For the Analysis Of the Italian Legislative Process", 6 July 2012, The Law Factory, (Sciences Po, CEE, Regards Citoyens, Médialab), Paris    

*	"Legislative processes as sequences: exploring the temporal dimension of law-making by means of sequence analysis", 10-15 April 2012, ECPR Joint Session 2012, Antwerp 

*	"Legislative processes as sequences: exploring the temporal dimension of law-making by means of sequence analysis", 6-8 June 2012, Lausanne Conference on Sequence Analysis, Lausanne   

*	"The evolution of EU law: analysing the longevity of EU legislation", 16-18 June 2011, 2011 EPSA General Conference, Dublin  

*	"The impact of party priorities on Italian law-making from the First to the Second Republic", 17-18 June 2010, 2010 Comparative Policy Agendas Conference, University of Washington, Seattle   

*	"The impact of party priorities on Italian law-making from the First to the Second Republic", 20-21 May 2010, "Political Parties and Comparative Policy Agendas: an ESF Workshop on Political Parties and their Positions, and Policy Agendas", University of Manchester, UK  

*	"Exploring why Italian executives fail to exercise the legislative powers they are delegated", 14-15 January 2010, the "International conference on democracy as idea and practice", University of Oslo, Norway
   
*	"Exploring why Italian executives do not exercise the legislative powers they are delegated", 9-12 September 2009, 2009 ECPR General Conference, Potsdam   
  
*	"Leading governments and unwilling legislators. The European Union and the Italian Law making (1987-2006)", Hague, 17 June 2009, "Delors' Myth Workshop 2: The scope and impact of Europeanization of law production"   
  
*	"The regional dimension of EU policy implementation", 25-27 September 2008, "Fourth Pan-European Conference on EU Politics (ECPR)", Riga     

*	"The pace of the legislative process. A diachronic analysis of the Italian legislature (1996-2006)", 4-6 September 2008, 2008 SISP (Italian Political Science Association) annual conference", Pavia

*	"The timely transposition of EU directives in Italy: do political priorities matter?",  11-16 April 2008, ECPR Joint sessions of workshops, Workshop "The Long Arm of EU Law", Rennes  
  
## ADDITIONAL TRAINING
* **Mar 2017**	ECPR Winter School in Methods and Techniques, Bamberg, Germany  
    One-week course in 'Time-series Analysis'.   
     
* **Feb 2012**	ECPR Winter School in Methods and Techniques, Vienna, Austria  
    One-week course in 'Sequence Analysis'.   
    
*	**Jun 2010** Five day workshop on sequence analysis for political scientists
Tools for text workshop, University of Washington, Seattle, US     
    Two-day workshop covering a range of content analysis approaches: Manual Annotation; Unsupervised Learning; Supervised Learning; Dimensional Scaling.   
    
* **Mar 2010**	Oxford Spring School, Oxford, UK  
    One-week course in "Modern Regression".
    
* **Jun 2009**	Empirical Implications of Theoretical Models, Mannheim, Germany  
    The two-week summer school focused on modelling techniques and methods of empirical testing theoretical models in the social science. 

* **Jul 2005**	Essex Summer School in Social Science Data Analysis, UK  
    The two-week summer school focused on Maths for Social Scientists, Survival Analysis, Mixing Methods

## OTHER PROFESSIONAL ACTIVITIES

### Translation	
* Il Mulino Publishing House, Bologna  
    Translation from English to Italian of the book "The government and politics of the European Union" by N.Nugent, London: MacMillan (2006, 6° ed.)

### Peer Review	  
https://publons.com/researcher/1429699/enrico-borghetto/ 

## LANGUAGE SKILLS
* Proficient user in both written and spoken English (ESOL Certificate in Advanced English) and Portuguese.
* School knowledge of Spanish, French and German.  

## OTHER SKILLS
* R, Rmarkdown 
* Ms Office
* SQL
* SPARQL
* Python